server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters: 
            - AuthFilter
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          filters: 
            - AuthFilter
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
          filters: 
            - AuthFilter
  