server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
  
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:9000/realms/Helpet/protocol/openid-connect/auth
            userinfo-uri: http://localhost:9000/realms/Helpet/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:9000/realms/Helpet/protocol/openid-connect/token
          registration:
            helpet-client:
              provider: keycloak
              client-id: helpet-client
              client-secret: 
              authorization-grant-type:
              redirect-uri: 