
server:
    port : 8000
spring:
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/Juanllamasares/Helpet-app-microservices
                    search-paths: config-data
    application: 
        name: config-service